# development:
#  adapter: sqlite3
#  database: db/development.sqlite3
#  pool: 5
#  timeout: 5000

 development:
  adapter: postgresql
  encoding: unicode
  database: invebox_development
  pool: 5
  username: richardtrussler
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: invebox_test
  pool: 5
  username: richardtrussler
  host: localhost
